service: codepipelinemonitoring
frameworkVersion: '3'

provider:
  name: aws
  stage: dev  # Get the stage from the environment variable TARGET
  region: ap-south-1  # Use AWS_REGION from the environment variables
  runtime: python3.12
  timeout: 900
  environment:
    TARGET_CLUSTER: my-company
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
        - cloudwatch:*
        - lambda:*
      Resource: 
        - "*"

  enviroment:
    TARGET: dev


  tags:
    Name: my-monitoring
    Project: Mycompany


functions:
  codepipelineMonitoring:
    handler: handler.hello
    events:
      - eventBridge:
          pattern:
            source:
              - "aws.codepipeline"
            detail-type:
              - "CodePipeline Pipeline Execution State Change"
          target:
            arn: arn:aws:lambda:ap-south-1:248189941331:function:codepipelineMonitoring